import smtplib
from email.message import EmailMessage
from pathlib import Path

signature = "\n\nThis report is generated by Payroll Solutions Electronic "
signature += "Reporting System (ERS).  For questions concerning the format of "
signature += "the report, please email helpdesk@payrollsolutions.cc, please "
signature += "include your company name, that you are emailing about an ERS "
signature += """report and the subject from the ERS email.

Do not reply directly to this email, this mailbox is not monitored.

Thank you,

Payroll Solutions Inc.
"""

def Clean_header(value: str) -> str:
    return value.replace("\n","").replace("\r","").strip()


def send_message_with_attachment(toEmail:str, body_text:str,attachment_path:str):
    SMTP_SERVER = "smtp-hve.office365.com"
    SMTP_PORT = "587"
    EMAIL_SENDER = "notifications@payrollsolutions.cc"
    EMAIL_PASSWORD = "6a3233bA42?"

    subject = "ERS Report"

    body_text += signature

    path = Path(attachment_path)

    if not path.exists():
        raise FileNotFoundError(f"Excel file not found: {path}")
    
    if path.suffix.lower() not in [".xlsx", ".xls"]:
        raise ValueError("Attachment must be an Excel file (.xlsx or .xls)")


    msg = EmailMessage()
    msg.set_content(body_text)
    msg['Subject'] = subject
    msg['To'] = toEmail
    msg['From'] = EMAIL_SENDER

    mime_map = {
        ".xlsx": (
            "application",
            "vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        ),
        ".xls": (
            "application",
            "vnd.ms-excel",
        ),
    }

    maintype, subtype = mime_map(path.suffix.lower())

    safe_filename = path.name.replace("\n","").replace("\r","")

    with open(path, "rb") as f:
        msg.add_attachment(
            f.read(),
            maintype=maintype,
            subtype = subtype,
            filename = safe_filename,
        )

    try:
        with smtplib.SMTP(SMTP_SERVER,SMTP_PORT) as server:
            server.starttls()
            server.login(EMAIL_SENDER,EMAIL_PASSWORD)
            server.send_message(msg)
    except Exception as e:
        print(f"Failed to send email to {toEmail}: {e}")


def send_message(toEmail:str, body_text:str):
    SMTP_SERVER = "smtp-hve.office365.com"
    SMTP_PORT = "587"
    EMAIL_SENDER = "notifications@payrollsolutions.cc"
    EMAIL_PASSWORD = "6a3233bA42?"
    

    subject = "ERS Message"


    body_text += signature

    msg = EmailMessage()
    msg.set_content(body_text)
    msg['Subject'] = subject
    msg['To'] = toEmail
    msg['From'] = EMAIL_SENDER

    try:
        with smtplib.SMTP(SMTP_SERVER,SMTP_PORT) as server:
            server.starttls()
            server.login(EMAIL_SENDER,EMAIL_PASSWORD)
            server.send_message(msg)
    except Exception as e:
        print(f"Failed to send email to {toEmail}: {e}")